apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fake-acme
  namespace: fake-acme
  labels:
    app: fake-acme
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fake-acme
  namespace: fake-acme
  labels:
    app: fake-acme
spec:
  output:
    to:
      kind: ImageStreamTag
      name: fake-acme:latest
  source:
    type: Git
    git:
      uri: https://github.com/agonzalezrh/fake-acme-endpoint.git
      ref: main
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: fake-acme-webhook-secret
    - type: Generic
      generic:
        secret: fake-acme-webhook-secret